apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mnpdbapiservice
  name: mnpdbapiservice-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mnpdbapiservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mnpdbapiservice
    spec:
      containers:
      - image: rameshsubramani/messagespark:latest
        name: mnpdbapiservice-v1
        ports:
        - containerPort: 8084
